<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxjN2xI\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxjN2xI/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKxjN2xI.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKxjN2xI\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKxjN2xI\App_KernelProdContainer([
    'container.build_hash' => 'KxjN2xI',
    'container.build_id' => 'e6ef9f4c',
    'container.build_time' => 1672669327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxjN2xI');
