<?php

namespace ContainerKxjN2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhCZwihService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.jhCZwih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jhCZwih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actionRepo' => ['privates', 'App\\Repository\\ActionRepository', 'getActionRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\AssociationsRepository', 'getAssociationsRepositoryService', false],
        ], [
            'actionRepo' => 'App\\Repository\\ActionRepository',
            'repo' => 'App\\Repository\\AssociationsRepository',
        ]);
    }
}
