<?php

namespace ContainerKxjN2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssociationsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.hAM5K.0.App\Entity\Associations' shared service.
     *
     * @return \App\Entity\Associations
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hAM5K.0": it references class "App\\Entity\\Associations" but no such service exists.');
    }
}
