<?php

namespace ContainerKxjN2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ActionRepository' shared autowired service.
     *
     * @return \App\Repository\ActionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ActionRepository'] = new \App\Repository\ActionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
