<?php

namespace ContainerKxjN2xI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'mailer.transports' shared service.
     *
     * @return \Symfony\Component\Mailer\Transport\Transports
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['mailer.transports'] = (new \Symfony\Component\Mailer\Transport(new RewindableGenerator(function () use ($container) {
            yield 0 => $container->load('getMailer_TransportFactory_GmailService');
            yield 1 => $container->load('getMailer_TransportFactory_NullService');
            yield 2 => $container->load('getMailer_TransportFactory_SendmailService');
            yield 3 => $container->load('getMailer_TransportFactory_NativeService');
            yield 4 => $container->load('getMailer_TransportFactory_SmtpService');
        }, 5)))->fromStrings(['main' => $container->getEnv('MAILER_DSN')]);
    }
}
