<?php

namespace ContainerNg1xJRW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HAM5K_0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hAM5K.0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hAM5K.0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'assoc' => ['privates', '.errored..service_locator.hAM5K.0.App\\Entity\\Associations', NULL, 'Cannot autowire service ".service_locator.hAM5K.0": it references class "App\\Entity\\Associations" but no such service exists.'],
            'assocRepo' => ['privates', 'App\\Repository\\AssociationsRepository', 'getAssociationsRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'assoc' => 'App\\Entity\\Associations',
            'assocRepo' => 'App\\Repository\\AssociationsRepository',
            'entityManager' => '?',
            'repo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
