<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5QF0vm3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5QF0vm3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5QF0vm3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5QF0vm3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5QF0vm3\App_KernelDevDebugContainer([
    'container.build_hash' => '5QF0vm3',
    'container.build_id' => '4a6dadd5',
    'container.build_time' => 1673346915,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5QF0vm3');
